Update chrooter

diff --git a/chrooter b/chrooter
--- a/chrooter
+++ b/chrooter
@@ -77,133 +77,133 @@ fi
 
 # Sanitization for Mount Directory variable
 sanitize_mount_directory() {
-	destdir="$1"
+	destdir_smd="$1"
 
-		# Sanity check for destdir
-	if [ -z "$destdir" ]; then
+		# Sanity check for destdir_smd
+	if [ -z "$destdir_smd" ]; then
 		die 2 "Function 'sanitize_mount_directory' expects argument with path to mount directory which is not provided"
 
-	elif [ -n "$destdir" ]; then
-		debug "Variable destdir in function 'sanitize_mount_directory' is set on '$destdir'"
+	elif [ -n "$destdir_smd" ]; then
+		debug "Variable destdir_smd in function 'sanitize_mount_directory' is set on '$destdir_smd'"
 
-		# Check if destdir is valid directory
-		if [ ! -d "$destdir" ]; then
-			die 1 "First argument '$destdir' in function 'sanitize_mount_directory' is not a valid directory"
-		elif [ -d "$destdir" ]; then
-			debug "In function 'sanitize_mount_directory' variable destdir stores a value of valid directory"
+		# Check if destdir_smd is valid directory
+		if [ ! -d "$destdir_smd" ]; then
+			die 1 "First argument '$destdir_smd' in function 'sanitize_mount_directory' is not a valid directory"
+		elif [ -d "$destdir_smd" ]; then
+			debug "In function 'sanitize_mount_directory' variable destdir_smd stores a value of valid directory"
 		else
-			die 255 "sanitize_mount_directory, destdir directory check"
+			die 255 "sanitize_mount_directory, destdir_smd directory check"
 		fi
 
 		# Enforce FSH-3.0
-		case "$destdir" in
-			/mnt/*) debug "Function 'sanitize_mount_directory' - Destdir '$destdir' is valid" ;;
-			*) warn "Mount directories should be mounted in /mnt directory not $destdir"
+		case "$destdir_smd" in
+			/mnt/*) debug "Function 'sanitize_mount_directory' - destdir_smd '$destdir_smd' is valid" ;;
+			*) warn "Mount directories should be mounted in /mnt directory not $destdir_smd"
 		esac
 
-		if [ ! -e "$destdir/etc" ] && [ -z "$forced" ]; then
-			die 1 "Unable to find /etc directory in $destdir directory, assuming invalid mount directory, use --force to override if needed."
-		elif [ ! -e "$destdir/etc" ] && [ -n "$forced" ]; then
-			warn "Directory '$destdir/etc' is not found, but forced is used"
-		elif [ -e "$destdir/etc" ]; then
-			debug "Directory '$destdir' is valid directory for chroot assuming checking for '$destdir/etc'"
+		if [ ! -e "$destdir_smd/etc" ] && [ -z "$forced" ]; then
+			die 1 "Unable to find /etc directory in $destdir_smd directory, assuming invalid mount directory, use --force to override if needed."
+		elif [ ! -e "$destdir_smd/etc" ] && [ -n "$forced" ]; then
+			warn "Directory '$destdir_smd/etc' is not found, but forced is used"
+		elif [ -e "$destdir_smd/etc" ]; then
+			debug "Directory '$destdir_smd' is valid directory for chroot assuming checking for '$destdir_smd/etc'"
 		else
-			die 255 "sanitize_mount_directory, destdir/etc check"
+			die 255 "sanitize_mount_directory, destdir_smd/etc check"
 		fi
 
 	else
-		die 255 "sanitize_mount_directory, destdir"
+		die 255 "sanitize_mount_directory, destdir_smd"
 
 	fi
 
-	unset destdir
+	unset destdir_smd
 }
 
 # Mount required filesystems for chrooting
 ## Reference: https://wiki.gentoo.org/wiki/Chroot#Configuration
 mount_required_fs() {
-	destdir="$1"
+	destdir_mrf="$1"
 
-	# Sanitization - Expecting $destdir="/mnt/something"
-	sanitize_mount_directory "$destdir"
+	# Sanitization - Expecting $destdir_mrf="/mnt/something"
+	sanitize_mount_directory "$destdir_mrf"
 
 	# Mount /dev
-	if ! grep -qF "$destdir/dev" /proc/mounts; then
-		mount --rbind /dev "$destdir/dev/" || die 1 "Unable to mount '/dev' as rbind on '$destdir/dev'"
-		mount --make-rslave "$destdir/dev" || die 1 "Unable to mount '/dev' as '-make-rslave' on '$destdir/dev'"
-	elif grep -qF "$destdir/dev" /proc/mounts; then
+	if ! grep -qF "$destdir_mrf/dev" /proc/mounts; then
+		mount --rbind /dev "$destdir_mrf/dev/" || die 1 "Unable to mount '/dev' as rbind on '$destdir_mrf/dev'"
+		mount --make-rslave "$destdir_mrf/dev" || die 1 "Unable to mount '/dev' as '-make-rslave' on '$destdir_mrf/dev'"
+	elif grep -qF "$destdir_mrf/dev" /proc/mounts; then
 		# FIXME: This may output if --rbind above fails
-		debug "Directory '$destdir/dev' is already mounted"
+		debug "Directory '$destdir_mrf/dev' is already mounted"
 	else
 		die 255 "mount_reguired_fs, dev"
 	fi
 
 	# Mount /sys
-	if ! grep -qF "$destdir/sys" /proc/mounts; then
-		mount --bind /sys "$destdir/sys/" || die 1 "Unable to mount '/sys' to '$destdir/sys' as bind which is required"
-	elif grep -qF "$destdir/sys" /proc/mounts; then
-		debug "Directory '$destdir/sys' is already mounted"
+	if ! grep -qF "$destdir_mrf/sys" /proc/mounts; then
+		mount --bind /sys "$destdir_mrf/sys/" || die 1 "Unable to mount '/sys' to '$destdir_mrf/sys' as bind which is required"
+	elif grep -qF "$destdir_mrf/sys" /proc/mounts; then
+		debug "Directory '$destdir_mrf/sys' is already mounted"
 	else
 		die 255 "mount_required_fs, sys"
 	fi
 
 	# Mount /tmp
-	if ! grep -qF "$destdir/tmp" /proc/mounts; then
-		mount --rbind /tmp "$destdir/tmp" || die 1 "Unable to mount '$destdir/tmp' as '--bind' on '/tmp'"
-		mount --make-rslave "$destdir/tmp" || die 1 "Unable to mount '/tmp' to '$destdir/tmp' as '--make-rbind' which is required"
-	elif grep -qF "$destdir/tmp" /proc/mounts; then
+	if ! grep -qF "$destdir_mrf/tmp" /proc/mounts; then
+		mount --rbind /tmp "$destdir_mrf/tmp" || die 1 "Unable to mount '$destdir_mrf/tmp' as '--bind' on '/tmp'"
+		mount --make-rslave "$destdir_mrf/tmp" || die 1 "Unable to mount '/tmp' to '$destdir_mrf/tmp' as '--make-rbind' which is required"
+	elif grep -qF "$destdir_mrf/tmp" /proc/mounts; then
 		# FIXME: This may trigger if --rbind above failed
-		debug "Directory '$destdir/tmp' is already mounted"
+		debug "Directory '$destdir_mrf/tmp' is already mounted"
 	else
 		die 255 "mount_required_fs, tmp"
 	fi
 
 	# Mount /proc
-	#if ! grep -qF "$destdir/proc" /proc/mounts;	then { mount --types proc none "$destdir/proc/" || die 0 "Unable to mount '/proc' on 'none' which is required";}; fi
+	#if ! grep -qF "$destdir_mrf/proc" /proc/mounts;	then { mount --types proc none "$destdir_mrf/proc/" || die 0 "Unable to mount '/proc' on 'none' which is required";}; fi
 	# HOTFIX, fuck everything
 	# FIXME!
-	mount --types proc none "$destdir/proc/" 2>/dev/null
+	mount --types proc none "$destdir_mrf/proc/" 2>/dev/null
 
-	unset destdir
+	unset destdir_mrf
 }
 
 # Perform chroot
 chrooter() {
-	destdir="$1"
+	destdir_crt="$1"
 	command="$2"
 
-	# Sanitization - Expecting $destdir="/mnt/something"
-	sanitize_mount_directory "$destdir"
+	# Sanitization - Expecting $destdir_crt="/mnt/something"
+	sanitize_mount_directory "$destdir_crt"
 
 	# Mount everything in chroot
 	# FIXME: Sanitize
-	{ chroot "$destdir" mount -a && info "filesystems has been mounted on $destdir" ;} || warn "Unable to mount all filesystems on $destdir"
+	{ chroot "$destdir_crt" mount -a && info "filesystems has been mounted on $destdir_crt" ;} || warn "Unable to mount all filesystems on $destdir_crt"
 
 	# Perform chroot
 	if [ -n "$command" ]; then
-		chroot "$destdir" "$command" || die 1 "Unable to Change Root from '$destdir' with command '$command'"
+		chroot "$destdir_crt" "$command" || die 1 "Unable to Change Root from '$destdir_crt' with command '$command'"
 	elif [ -z "$command" ]; then
-		chroot "$destdir" /bin/bash || die 1 "Unable to Change Root from '$destdir' to /bin/bash"
+		chroot "$destdir_crt" /bin/bash || die 1 "Unable to Change Root from '$destdir_crt' to /bin/bash"
 	fi
 
-	unset destdir command
+	unset destdir_crt command
 }
 
 # Take down chroot
 kill_chrooter() {
-	destdir="$1"
+	destdir_kc="$1"
 
-	# Sanitization - Expecting $destdir="/mnt/something"
-	sanitize_mount_directory "$destdir"
+	# Sanitization - Expecting $destdir_kc="/mnt/something"
+	sanitize_mount_directory "$destdir_kc"
 
-	if grep -qF $destdir /proc/mounts; then
+	if grep -qF $destdir_kc /proc/mounts; then
 		fixme "Unable to kill chroot on runtime (/dev preventing umount)"
-		umount -R "$destdir" || die 1 "Unable to unmount $destdir"
-	elif ! grep -qF "$destdir" /proc/mounts; then
-		info "Directory $destdir is already not mounted, skipping.."
+		umount -R "$destdir_kc" || die 1 "Unable to unmount $destdir_kc"
+	elif ! grep -qF "$destdir_kc" /proc/mounts; then
+		info "Directory $destdir_kc is already not mounted, skipping.."
 		return 0
 	else
-		die 255 "kill_chrooter, checking for destdir"
+		die 255 "kill_chrooter, checking for destdir_kc"
 	fi
 }
 
