chrooter: Making it more production ready

diff --git a/chrooter b/chrooter
--- a/chrooter
+++ b/chrooter
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/sh
 # Abstract: CHange ROOT into desired directory (chrooter).
 # Created by github.com/kreyren under GNUv3 (https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html)
 
@@ -6,85 +6,189 @@
 # https://github.com/RXT067/Scripts/tree/kreyren/kreypi
 
 # Sanitycheck for fetch
-if ! command -v 'wget' >/dev/null && [ ! -e "/lib/bash/kreypi.bash" ]; then printf "FATAL: This script requires 'wget' to be executable for downloading of kreypi (https://github.com/RXT067/Scripts/tree/kreyren/kreypi) for further sourcing\n" ; exit 1 ; fi
+if ! command -v 'wget' >/dev/null && [ ! -e "/lib/bash/kreypi.bash" ]; then
+    printf 'FATAL: %s\n' "This script requires 'wget' to be executable for downloading of kreypi (https://github.com/RXT067/Scripts/tree/kreyren/kreypi) for further sourcing\n"
+    exit 1
+fi
 
 # Sanitycheck for /lib/bash
 # shellcheck disable=SC2154
-[ ! -e "/lib/bash" ] && { mkdir -p "/lib/bash" || printf "ERROR: Unable to make a new directory in /lib/bash\n" ; exit 1 ;} || { [ -n "$debug" ] && printf "DEBUG: Directory in '/lib/bash' already exists\n" ;}
+if [ ! -e "/lib/bash" ]; then
+    mkdir -p "/lib/bash" || printf 'ERROR: %s\n' "Unable to make a new directory in /lib/bash"
+    exit 1
+elif [ -e "/lib/bash" ]; then
+    [ -n "$debug" ] && printf 'DEBUG: %s\n' "Directory in '/lib/bash' already exists\n"
+fi
 
 # Fetch
-[ ! -e "/lib/bash/kreypi.bash" ] && { wget 'https://raw.githubusercontent.com/RXT067/Scripts/kreyren/kreypi/kreypi.bash' -O '/lib/bash/kreypi.bash' || printf '%s\n' "Unable to download kreypi from 'https://raw.githubusercontent.com/RXT067/Scripts/kreyren/kreypi/kreypi.bash' -O '/lib/bash/kreypi.bash' in '/lib/bash/kreypi.bash'" ; exit 1 ;} || [ -n "$debug" ] && printf "DEBUG: File '/lib/bash/kreypi.bash' already exists\n"
+if [ ! -e "/lib/bash/kreypi.bash" ]; then
+    wget https://raw.githubusercontent.com/RXT067/Scripts/kreyren/kreypi/kreypi.bash -O '/lib/bash/kreypi.bash' || printf 'FATAL: %s\n' "Unable to download kreypi from 'https://raw.githubusercontent.com/RXT067/Scripts/kreyren/kreypi/kreypi.bash' in '/lib/bash/kreypi.bash'"
+    exit 1
+elif [ -e "/lib/bash/kreypi.bash" ]; then
+    [ -n "$debug" ] && printf 'DEBUG: %s\n' "File '/lib/bash/kreypi.bash' already exists"
+fi
 
 # Source
 if [ -e "/lib/bash/kreypi.bash" ]; then
-	# 'source' can not be used on POSIX sh
-	. "/lib/bash/kreypi.bash" || { printf "FATAL: Unable to source '/lib/bash/kreypi.bash'\n" ; exit 1 ;}
-  [ -n "$debug" ] && printf "DEBUG: Kreypi in '/lib/bash/kreypi.bash' has been successfully sourced\n"
+    # 'source' can not be used on POSIX sh
+    # shellcheck disable=SC1091
+    . "/lib/bash/kreypi.bash" || { printf "FATAL: Unable to source '/lib/bash/kreypi.bash'\n" ; exit 1 ;}
+    [ -n "$debug" ] && printf "DEBUG: Kreypi in '/lib/bash/kreypi.bash' has been successfully sourced"
 elif [ ! -e "/lib/bash/kreypi.bash" ]; then
 	printf "FATAL: Unable to source '/lib/bash/kreypi.bash' since path doesn't exists\n"
 fi
 
 ### END OF KREYPI INIT ###
 
-# Export shell-compatibility
-shellcompat
+# Sanitization for Mount Directory variable
+sanitize_mount_directory() {
+    destdir="$1"
 
-sanitize_mount_directory() { # Sanitization for Mount Directory variable
-	[ -z "$1" ] && die 2 "Function ${FUNCNAME[0]} expects argument with path to mount directory which is not provided"
-	[ ! -d "$1" ] && die "First argument ($1) of function ${FUNCNAME[0]} is not a valid directory"
-	case "$1" in '/mnt/*') warn "Mount directories should be mounted in /mnt directory not $1"; esac
-	[ ! -e "$1/etc" ] && [ -z "$forced" ] && die 1 "Unable to find /etc directory in $1 directory, assuming invalid mount directory, use --force to override if needed."
+    # Sanity check for destdir
+	if [ -z "$destdir" ]; then
+        die 2 "Function 'sanitize_mount_directory' expects argument with path to mount directory which is not provided"
+
+    elif [ -n "$destdir" ]; then
+        debug "Variable destdir in function 'saniti' is set on '$destdir'"
+
+        # Check if destdir is valid directory
+        if [ ! -d "$destdir" ]; then
+            die 1 "First argument '$destdir' in function 'sanitize_mount_directory' is not a valid directory"
+        elif [ -d "$destdir" ]; then
+            debug "In function 'sanitize_mount_directory' variable destdir stores a value of valid directory"
+        else
+            die 255 "sanitize_mount_directory, destdir directory check"
+        fi
+
+        # Enforce FSH-3.0
+	    case "$destdir" in
+            '/mnt/*') true ;;
+            *) warn "Mount directories should be mounted in /mnt directory not $destdir"
+        esac
+
+        if [ ! -e "$destdir/etc" ] && [ -z "$forced" ]; then
+            die 1 "Unable to find /etc directory in $destdir directory, assuming invalid mount directory, use --force to override if needed."
+        elif [ ! -e "$destdir/etc" ] && [ -n "$forced" ]; then
+            debug "Directory '$destdir/etc' is not found, but forced is used"
+        else
+            die 255 "sanitize_mount_directory, destdir/etc check"
+        fi
+
+    else
+        die 255 "sanitize_mount_directory, destdir"
+
+    fi
+
+    unset destdir
 }
 
-mount_required_fs() { # Mount required filesystems for chrooting
-	## Sanitization - Expecting 1="/mnt/something"
-	sanitize_mount_directory "$1"
-	## Action
-	### Reference: https://wiki.gentoo.org/wiki/Chroot#Configuration
-	### /dev
-	if ! grep -qF "$1/dev" /proc/mounts; then { mount --rbind /dev "$1/dev/" || die 1 "Unable to mount '/dev' as rbind on '$1/dev'" ;} && { mount --make-rslave "$1/dev" || die 1 "Unable to mount '/dev' as '-make-rslave' on '$1/dev'" ;}; fi
-	### /sys
-	if ! grep -qF "$1/sys" /proc/mounts; then { mount --bind /sys "$1/sys/" || die 0 "Unable to mount '/sys' to '$1/sys' as bind which is required" ;}; fi
-	### /tmp
-	if ! grep -qF "$1/tmp" /proc/mounts; then { mount --rbind /tmp "$1/tmp" || die 1 "Unable to mount '$1/tmp' as '--bind' on '/tmp'";} && { mount --make-rslave "$1/tmp" || die 0 "Unable to mount '/tmp' to '$1/tmp' as '--make-rbind' which is required";}; fi
-	### /proc
-	#if ! grep -qF "$1/proc" /proc/mounts;	then { mount --types proc none "$1/proc/" || die 0 "Unable to mount '/proc' on 'none' which is required";}; fi
+# Mount required filesystems for chrooting
+## Reference: https://wiki.gentoo.org/wiki/Chroot#Configuration
+mount_required_fs() {
+    destdir="$1"
+
+	# Sanitization - Expecting $destdir="/mnt/something"
+	sanitize_mount_directory "$destdir"
+
+	# Mount /dev
+	if ! grep -qF "$destdir/dev" /proc/mounts; then
+        mount --rbind /dev "$destdir/dev/" || die 1 "Unable to mount '/dev' as rbind on '$destdir/dev'" 
+        mount --make-rslave "$destdir/dev" || die 1 "Unable to mount '/dev' as '-make-rslave' on '$destdir/dev'"
+    elif ! grep -qF "$destdir/dev" /proc/mounts; then
+        # FIXME: This may output if --rbind above fails
+        debug "Directory '$destdir/dev' is already mounted"
+    else
+        die 255 "mount_reguired_fs, dev"
+    fi
+
+	# Mount /sys
+	if ! grep -qF "$destdir/sys" /proc/mounts; then
+        mount --bind /sys "$destdir/sys/" || die 1 "Unable to mount '/sys' to '$destdir/sys' as bind which is required" 
+    elif grep -qF "$destdir/sys" /proc/mounts; then
+        debug "Directory '$destdir/sys' is already mounted"
+    else
+        die 255 "mount_required_fs, sys"
+    fi
+
+	# Mount /tmp
+	if ! grep -qF "$destdir/tmp" /proc/mounts; then
+        mount --rbind /tmp "$destdir/tmp" || die 1 "Unable to mount '$destdir/tmp' as '--bind' on '/tmp'"
+        mount --make-rslave "$destdir/tmp" || die 1 "Unable to mount '/tmp' to '$destdir/tmp' as '--make-rbind' which is required"
+    elif ! grep -qF "$destdir/tmp" /proc/mounts; then
+        # FIXME: This may trigger if --rbind above failed
+        debug "Directory '$destdir/tmp' is already mounted"
+    else
+        die 255 "mount_required_fs, tmp"
+    fi
+
+	# Mount /proc
+	#if ! grep -qF "$destdir/proc" /proc/mounts;	then { mount --types proc none "$destdir/proc/" || die 0 "Unable to mount '/proc' on 'none' which is required";}; fi
 	# HOTFIX, fuck everything
-	mount --types proc none "$1/proc/" 2>/dev/null
+    # FIXME!
+	mount --types proc none "$destdir/proc/" 2>/dev/null
+
+    unset destdir
 }
 
-chrooter() { # Perform chroot
-	## Sanitization - Expecting 1="/mnt/something"
-	sanitize_mount_directory "$1"
-	## Action
-	### Mount everything in chroot
-	{ chroot "$1" mount -a && info "filesystems has been mounted on $1" ;} || warn "Unable to mount all filesystems on $1"
-	### Perform chroot
-	if [ -n "$2" ]; then { chroot "$1" "$2" || die 0 "Unable to Change root from $1 to $2" ;}
-	elif [ -z "$2" ]; then { chroot "$1" /bin/bash || die 0 "Unable to Change root from $1 to /bin/bash";}
+# Perform chroot
+chrooter() {
+    destdir="$1"
+    command="$2"
+
+	# Sanitization - Expecting $destdir="/mnt/something"
+	sanitize_mount_directory "$destdir"
+
+	# Mount everything in chroot
+    # FIXME: Sanitize
+	{ chroot "$destdir" mount -a && info "filesystems has been mounted on $destdir" ;} || warn "Unable to mount all filesystems on $destdir"
+
+	# Perform chroot
+	if [ -n "$command" ]; then
+        chroot "$destdir" "$command" || die 0 "Unable to Change root from '$destdir' with command '$command'"
+	elif [ -z "$command" ]; then
+        chroot "$destdir" /bin/bash || die 0 "Unable to Change root from '$destdir' to /bin/bash"
 	fi
+
+    unset destdir command
 }
 
-kill_chrooter() { # Take down chroot
-	## Sanitization - Expecting 1="/mnt/something"
-	sanitize_mount_directory "$1"
-	[ "$(mount | grep -o "$1" -m '1')" == "$1" ] && warn "FIXME: Unable to kill chroot on runtime (/dev preventing umount)"
-	if ! grep -qF "$1" /proc/mounts; then { warn "Function ${FUNCNAME[0]} was unable to detect mounted $1, skipping.." && return ;} fi
-	## Action
-	umount -R "$1" || die 0 "Unable to umount $1"
+# Take down chroot
+kill_chrooter() {
+    destdir="$1"
+
+	# Sanitization - Expecting $destdir="/mnt/something"
+	sanitize_mount_directory "$destdir"
+
+	if [ "$(mount | grep -o "$destdir" -m '1')" = "$destdir" ]; then
+        fixme "Unable to kill chroot on runtime (/dev preventing umount)"
+        umount -R "$destdir" || die 1 "Unable to unmount $destdir"
+	elif ! grep -qF "$destdir" /proc/mounts; then
+        info "Directory $destdir is already not mounted, skipping.."
+        return 0
+    else
+        die 255 "kill_chrooter, checking for destdir"
+    fi
 }
 
 # CODE
 checkroot "$@"
 
-while [ "$#" -gt 0 ]; do case "$1" in
+while [ "$#" -gt 1 ]; do case "$1" in
 	-f|--force) export forced="KREYREN"; shitf 1 ;;
 	-K|--kill) kill_chrooter "$2" ;;
-	/*) # TODO: Sanitize for path
+    # Allow full path only
+	/*)
 		mount_required_fs "$1"
+
 		chrooter "$1" "$2"
-		[ -n "$2" ] && shift 1
-		shift 1
+
+		if [ -n "$2" ]; then
+            shift 2
+        elif [ -n "$1" ] && [ -z "$2" ]; then
+            shift 1
+        else
+            die 255 "Arguments, shifting of full unix path"
+        fi
 	;;
-	*) die 1 "Unrecognized argument '$1' was parsed"
+	*) die 2 "Unrecognized argument '$1' was parsed"
 esac; done
