Update based on suggestion 1/2

diff --git a/mychroot b/mychroot
--- a/mychroot
+++ b/mychroot
@@ -4,6 +4,36 @@
 # Author      : github.com/kreyren
 # Licence     : GPLv2 (https://www.gnu.org/licenses/old-licenses/gpl-2.0.cs.html)
 
+## IMPROVEMENT 1+2
+#<01> kreyren: see following example:
+#<01> # ...() {   declare -A osnames=([gentoo]= [ubuntu]= [LFS]= [OpenSUSE]=);  if [[ $1 == --* && -v osnames["${1#--}"] ]]; then  echo -n checkroot "$@" '...  ';  set -- "${1#--}"; set -- "${1^^}";  echo '$@ is now' "$@";  DIR=/mnt/$1;  echo 'DIR is now' "$DIR";  else   echo showhelp;  fi; };    ... --gentoo
+#<shbot> 01: checkroot --gentoo ...  $@ is now GENTOO
+#<shbot> 01: DIR is now /mnt/GENTOO
+#<01> # ...() {   declare -A osnames=([gentoo]= [ubuntu]= [LFS]= [OpenSUSE]=);  if [[ $1 == --* && -v osnames["${1#--}"] ]]; then  echo -n checkroot "$@" '...  ';  set -- "${1#--}"; dirname=$1;  set -- "${1^^}";  echo '$@ is now' "$@";  DIR=/mnt/$dirname;  echo 'DIR is now' "$DIR";  else   echo showhelp;  fi; };    ... --ubuntu
+#<shbot> 01: checkroot --ubuntu ...  $@ is now UBUNTU
+#<shbot> 01: DIR is now /mnt/ubuntu
+#<01> # ...() {   declare -A osnames=([gentoo]= [ubuntu]= [LFS]= [OpenSUSE]=);  if [[ $1 == --* && -v osnames["${1#--}"] ]]; then  echo -n checkroot "$@" '...  ';  set -- "${1#--}"; dirname=$1;  set -- "${1^^}";  echo '$@ is now' "$@";  DIR=/mnt/$dirname;  echo 'DIR is now' "$DIR";  else   echo showhelp;  fi; };    ... --OpenSUSE
+#<shbot> 01: checkroot --OpenSUSE ...  $@ is now OPENSUSE
+#<shbot> 01: DIR is now /mnt/OpenSUSE
+#<01> # ...() {   declare -A osnames=([gentoo]= [ubuntu]= [LFS]= [OpenSUSE]=);  if [[ $1 == --* && -v osnames["${1#--}"] ]]; then  echo -n checkroot "$@" '...  ';  set -- "${1#--}"; dirname=$1;  set -- "${1^^}";  echo '$@ is now' "$@";  DIR=/mnt/$dirname;  echo 'DIR is now' "$DIR";  else   echo showhelp;  fi; };    ... something-else
+#<shbot> 01: showhelp
+#<kreyren> investigating ty for example
+#<01> kreyren: you see how it works, right?  we are using parameter expansions  ${1#--}, ${1^^},
+#<01> parameter expansions are explained in this channel's wiki:
+#<01> !pe
+#<greybot> Parameter Expansion expands parameters: "$foo", "$1". You can use it to perform string or array operations: "${file%.mp3}", "${0##*/}", "${files[@]: -4}". They should *always* be quoted. See: http://mywiki.wooledge.org/BashFAQ/073 and "Parameter Expansion" in man bash. Also see http://wiki.bash-hackers.org/syntax/pe.
+#<01> set operations, like checking if an element is in a set or finding set intersections, are often implemented in bash using associative arrays
+#<01> they are also explained in the wiki^
+#<02> https://github.com/RXT067/Scripts/blob/5c05fb6b4cec5bd51b86b7b274bc2466e98de944/mychroot#L50 :) [a-z][1-9] ;) there also can be things like vda, hda
+#<checkbot> 02: I think the problem is on line 50. You are missing a required space here. See 4 issues on https://shellcheck.net/?id=cb61796
+#<01> !assoc
+#<greybot> Associative Arrays map strings to strings (Bash 4): http://mywiki.wooledge.org/BashGuide/Arrays#Associative_Arrays
+#<kreyren> `[a-z][1-9]` good idea, adapted
+#<01> kreyren: you can check if special file (like /dev/sda1) is a disk using one of test or [ built-in commands or [[ syntax with -b test
+#<01> # help test | grep -- '  -b '
+#<shbot> 01:       -b FILE        True if file is block special.
+#<kreyren> Noted, investigating
+
 CALLME=KMC
 
 dependency () {
@@ -45,17 +75,23 @@ checkroot () {
 }
 
 chroot-me-senpaii () {
+DIR=/mnt/${1^^}
 
-	# Sanity check for $1_CHROOT
-	while [[ $1_CHROOT =! "/dev/sd[abcdefghijklmnopqrstuvwxyz][1-9]" ]]; do
-		echo "ERROR: $1_CHROOT is not /dev/sd[abcdefghijklmnopqrstuvwxyz][1-9]"
+	while [[ GO != @(Y|y) ]]; do
+		echo "We will mount and prepare for chroot to $DIR, continue? (y/n)"
+		read GO
+	done
+
+	# Sanity check for ${1^^}_CHROOT
+	while [[ ${1^^}_CHROOT =! "/dev/sd[a-z][1-9]" ]]; do
+		echo "ERROR: ${1^^}_CHROOT is not /dev/sd[a-z][1-9]"
 
 		echo "(R)etry, (M)anuall"
 		read CHOICE
 		if [[ CHOICE == @(M|m) ]]; then
 			# Expected /dev/{USER_INPUT}
-			echo "Enter $1_CHROOT variable manually:"
-			read $1_CHROOT
+			echo "Enter ${1^^}_CHROOT variable manually:"
+			read ${1^^}_CHROOT
 		fi
 	done
 
@@ -65,7 +101,7 @@ chroot-me-senpaii () {
 	fi
 
 	# Chroot in
-	mount $1_CHROOT $DIR || echo "FATAL: Mounting $GENTOO_CHROOT to $DIR failed!" && exit 0
+	mount ${1^^}_CHROOT $DIR || echo "FATAL: Mounting ${1^^}_CHROOT to $DIR failed!" && exit 0
 	mount --rbind /dev $DIR/dev || echo "ERROR: Unable to rbind /dev to $DIR/dev." 
 	mount --make-rslave $DIR/dev || echo "ERROR: Unable to make-rslave of $DIR/dev."
 	mount -t proc /proc $DIR/proc || echo "ERROR: Unable to mount proc."
@@ -74,46 +110,10 @@ chroot-me-senpaii () {
 	mount --rbind /tmp $DIR/tmp || echo "ERROR: Unable to rbind /tmp to $DIR/tmp"
 }
 
-showhelp () {
-	echo "KreyMyChroot uses environment variables to chroot into available filesystems on multiboot systems
---gentoo   : To chroot in gentoo system.
---ubuntu   : To chroot in ubuntu system.
---LFS      : To chroot in LFS system.
---OpenSUSE : To chroot in OpenSUSE system.
-	"
-}
-
 
 case $1 in
-# TODO: Grep $1, capitalize it and use
-	--gentoo)
-		checkroot $@
-		1=GENTOO
-		dependency
-		DIR=/mnt/gentoo
-		chroot-me-senpaii
-	;;
-	--ubuntu)
-		checkroot $@
-		1=UBUNTU
-		dependency
-		DIR=/mnt/ubuntu
-		chroot-me-senpaii
-	;;
-	--LFS)
-		checkroot $@
-		1=LFS
-		dependency
-		DIR=/mnt/LFS
-		chroot-me-senpaii
-	;;
-	--OpenSUSE)
-		checkroot $@
-		1=OPENSUSE
-		dependency
-		DIR=/mnt/OpenSUSE
-		chroot-me-senpaii
-	;;
 	*)
-		showhelp
+		checkroot $@
+		dependency
+		chroot-me-senpaii
 esac
